apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - config.yaml
  - secret.yaml
  - postgres.yaml
  - notification-service.yaml
  - ingestion-service.yaml
  - consensus-service.yaml
  - ingress.yaml
  - sensor-client.yaml